apiVersion: v1
kind: Namespace
metadata:
  name: pr-1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: pr-1
spec:
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: pr-1
  labels:
    app: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: pr-1
spec:
  ingressClassName: nginx
  rules:
    - host: pr-1.jodoi-pr-preview.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: app
                port:
                  number: 80
status:
  loadBalancer:
    ingress:
    - hostname: localhost
